name: comp430
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - freetype=2.10.4
  - gmpy2=2.0.8
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2020.2
  - joblib=1.0.0
  - jpeg=9b
  - kiwisolver=1.3.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - llvmlite=0.34.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.1.0
  - ninja=1.10.2
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pandas=1.1.3
  - pillow=8.0.1
  - pip=20.2.4
  - pycryptodome=3.9.9
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.7.0
  - pytz=2020.1
  - qt=5.9.7
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=50.3.1
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - sympy=1.7.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.4
  - typing_extensions=3.7.4.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.35.1
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - grpcio==1.34.0
    - grpcio-tools==1.34.0
    - pandasql==0.7.3
    - phe==1.4.0
    - protobuf==3.14.0
    - sqlalchemy==1.3.20
