# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication/communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication/communication.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!communication/communication.proto\"O\n\x0c\x43ontribution\x12\x16\n\x0e\x63ontributor_id\x18\x01 \x01(\x05\x12\x11\n\ttarget_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x63ontribution\x18\x03 \x01(\t\"/\n\x0bModelWeight\x12\x11\n\tdata_size\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\".\n\x0fPublicParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\'\n\rClientAddress\x12\x16\n\x0e\x63lient_address\x18\x01 \x01(\t\">\n\x11\x43lientInformation\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63lient_address\x18\x02 \x01(\t\"L\n\tPublicKey\x12\x14\n\x0cowner_client\x18\x01 \x01(\x05\x12\x15\n\rtarget_client\x18\x02 \x01(\x05\x12\x12\n\npublic_key\x18\x03 \x01(\x03\"\t\n\x07VoidMsg\"\x15\n\x03\x41\x63k\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xd6\x01\n\x06\x43lient\x12\'\n\tNewClient\x12\x12.ClientInformation\x1a\x04.Ack\"\x00\x12(\n\nInitialize\x12\x10.PublicParameter\x1a\x04.Ack\"\x00(\x01\x12,\n\x13ReceiveContribution\x12\r.Contribution\x1a\x04.Ack\"\x00\x12\x30\n\x0c\x43lientUpdate\x12\x0c.ModelWeight\x1a\x0c.ModelWeight\"\x00(\x01\x30\x01\x12\x19\n\x05Setup\x12\x08.VoidMsg\x1a\x04.Ack\"\x00\x32\xa5\x01\n\x06Server\x12\x36\n\x0eRegisterClient\x12\x0e.ClientAddress\x1a\x12.ClientInformation\"\x00\x12\x32\n\x0eReceiveClients\x12\x08.VoidMsg\x1a\x12.ClientInformation\"\x00\x30\x01\x12/\n\x14\x46orwardContributions\x12\r.Contribution\x1a\x04.Ack\"\x00(\x01\x62\x06proto3'
)




_CONTRIBUTION = _descriptor.Descriptor(
  name='Contribution',
  full_name='Contribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contributor_id', full_name='Contribution.contributor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='Contribution.target_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contribution', full_name='Contribution.contribution', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=116,
)


_MODELWEIGHT = _descriptor.Descriptor(
  name='ModelWeight',
  full_name='ModelWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_size', full_name='ModelWeight.data_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ModelWeight.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=165,
)


_PUBLICPARAMETER = _descriptor.Descriptor(
  name='PublicParameter',
  full_name='PublicParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PublicParameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='PublicParameter.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=213,
)


_CLIENTADDRESS = _descriptor.Descriptor(
  name='ClientAddress',
  full_name='ClientAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_address', full_name='ClientAddress.client_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=254,
)


_CLIENTINFORMATION = _descriptor.Descriptor(
  name='ClientInformation',
  full_name='ClientInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ClientInformation.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_address', full_name='ClientInformation.client_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=318,
)


_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_client', full_name='PublicKey.owner_client', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_client', full_name='PublicKey.target_client', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='PublicKey.public_key', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=396,
)


_VOIDMSG = _descriptor.Descriptor(
  name='VoidMsg',
  full_name='VoidMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=407,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Ack.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=430,
)

DESCRIPTOR.message_types_by_name['Contribution'] = _CONTRIBUTION
DESCRIPTOR.message_types_by_name['ModelWeight'] = _MODELWEIGHT
DESCRIPTOR.message_types_by_name['PublicParameter'] = _PUBLICPARAMETER
DESCRIPTOR.message_types_by_name['ClientAddress'] = _CLIENTADDRESS
DESCRIPTOR.message_types_by_name['ClientInformation'] = _CLIENTINFORMATION
DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['VoidMsg'] = _VOIDMSG
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Contribution = _reflection.GeneratedProtocolMessageType('Contribution', (_message.Message,), {
  'DESCRIPTOR' : _CONTRIBUTION,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:Contribution)
  })
_sym_db.RegisterMessage(Contribution)

ModelWeight = _reflection.GeneratedProtocolMessageType('ModelWeight', (_message.Message,), {
  'DESCRIPTOR' : _MODELWEIGHT,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:ModelWeight)
  })
_sym_db.RegisterMessage(ModelWeight)

PublicParameter = _reflection.GeneratedProtocolMessageType('PublicParameter', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICPARAMETER,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:PublicParameter)
  })
_sym_db.RegisterMessage(PublicParameter)

ClientAddress = _reflection.GeneratedProtocolMessageType('ClientAddress', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTADDRESS,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:ClientAddress)
  })
_sym_db.RegisterMessage(ClientAddress)

ClientInformation = _reflection.GeneratedProtocolMessageType('ClientInformation', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFORMATION,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:ClientInformation)
  })
_sym_db.RegisterMessage(ClientInformation)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:PublicKey)
  })
_sym_db.RegisterMessage(PublicKey)

VoidMsg = _reflection.GeneratedProtocolMessageType('VoidMsg', (_message.Message,), {
  'DESCRIPTOR' : _VOIDMSG,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:VoidMsg)
  })
_sym_db.RegisterMessage(VoidMsg)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'communication.communication_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  })
_sym_db.RegisterMessage(Ack)



_CLIENT = _descriptor.ServiceDescriptor(
  name='Client',
  full_name='Client',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=433,
  serialized_end=647,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewClient',
    full_name='Client.NewClient',
    index=0,
    containing_service=None,
    input_type=_CLIENTINFORMATION,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='Client.Initialize',
    index=1,
    containing_service=None,
    input_type=_PUBLICPARAMETER,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveContribution',
    full_name='Client.ReceiveContribution',
    index=2,
    containing_service=None,
    input_type=_CONTRIBUTION,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClientUpdate',
    full_name='Client.ClientUpdate',
    index=3,
    containing_service=None,
    input_type=_MODELWEIGHT,
    output_type=_MODELWEIGHT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Setup',
    full_name='Client.Setup',
    index=4,
    containing_service=None,
    input_type=_VOIDMSG,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLIENT)

DESCRIPTOR.services_by_name['Client'] = _CLIENT


_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='Server',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=650,
  serialized_end=815,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterClient',
    full_name='Server.RegisterClient',
    index=0,
    containing_service=None,
    input_type=_CLIENTADDRESS,
    output_type=_CLIENTINFORMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveClients',
    full_name='Server.ReceiveClients',
    index=1,
    containing_service=None,
    input_type=_VOIDMSG,
    output_type=_CLIENTINFORMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ForwardContributions',
    full_name='Server.ForwardContributions',
    index=2,
    containing_service=None,
    input_type=_CONTRIBUTION,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
